# Generated by Django 4.0.2 on 2022-08-07 11:46

from django.db import migrations, models
import scripts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('converted_image', models.ImageField(upload_to='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='scripts/', validators=[scripts.models.validate_file_extension])),
                ('image', models.ImageField(upload_to='scripts/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
